server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis-mapper/*Mapper.xml
  type-aliases-package: org.daijie.springboot.orm.mybatis.model

demo:
  jdbc:
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&amp;charaterEncoding=utf-8
    username: root
jdbc:
  driverClass: com.mysql.jdbc.Driver
mapper:
  identity: MYSQL
  not-empty: false

logging:
  level:
    org:
      daijie:
        springboot : debug