server:
  port: 8080

spring:
  datasource:
    password: Shiji@2018
    url: jdbc:mysql://10.13.10.104:3306/test11?useUnicode=true&characterEncoding=UTF8
    username: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    org:
      daijie:
        springboot : debug